"""Fixture tests for resilient harness batch execution."""

import csv
import os
import shutil
import subprocess
import sys
from pathlib import Path


def run_command(*arguments: str, cwd: Path) -> None:
    """Run a required git setup command in the fixture repository."""
    subprocess.run(arguments, cwd=cwd, check=True, capture_output=True, encoding="utf-8")


def create_harness_repository(
    tmp_path: Path, failure_run: int, *, mutate_harness_script: bool = False
) -> tuple[Path, dict[str, str]]:
    """Create a tracked temporary repository with a deterministic fake Codex CLI."""
    repository = tmp_path / "repository"
    scripts_path = repository / "scripts"
    scripts_path.mkdir(parents=True)
    shutil.copy2("scripts/run_harness.sh", scripts_path / "run_harness.sh")
    shutil.copy2("scripts/harness_stats.py", scripts_path / "harness_stats.py")
    (repository / "prompt.txt").write_text("fixture prompt\n", encoding="utf-8")
    (repository / ".gitignore").write_text("harness_runs/\n__pycache__/\n", encoding="utf-8")
    run_command("git", "init", "--quiet", cwd=repository)
    run_command("git", "config", "user.email", "test@example.invalid", cwd=repository)
    run_command("git", "config", "user.name", "Harness Test", cwd=repository)
    run_command("git", "add", ".", cwd=repository)
    run_command("git", "commit", "--quiet", "-m", "fixture", cwd=repository)

    executable_directory = tmp_path / "bin"
    executable_directory.mkdir()
    count_path = tmp_path / "codex-count"
    fake_codex = executable_directory / "codex"
    fake_codex.write_text(
        "#!/usr/bin/env bash\n"
        "set -eu\n"
        'count_file="${CODEX_COUNT_FILE:?}"\n'
        'count="$(cat "$count_file" 2>/dev/null || echo 0)"\n'
        "count=$((count + 1))\n"
        'printf "%s\\n" "$count" > "$count_file"\n'
        'if [[ "$count" -eq 2 && -d src/cache_only/__pycache__ ]]; then exit 8; fi\n'
        "mkdir -p src/cache_only/__pycache__\n"
        "touch src/cache_only/__pycache__/module.cpython-313.pyc\n"
        'printf \'{"type":"turn.completed"}\\n\'\n'
        'if [[ "$count" -eq "${CODEX_FAILURE_RUN:?}" ]]; then exit 7; fi\n',
        encoding="utf-8",
    )
    if mutate_harness_script:
        fake_codex.write_text(
            fake_codex.read_text(encoding="utf-8")
            + 'printf "if then\\n" > scripts/run_harness.sh\n',
            encoding="utf-8",
        )
    fake_codex.chmod(0o755)
    snapshot_directory = tmp_path / "snapshots"
    snapshot_directory.mkdir()
    environment = {
        **os.environ,
        "PATH": f"{executable_directory}{os.pathsep}{os.environ['PATH']}",
        "CODEX_COUNT_FILE": str(count_path),
        "CODEX_FAILURE_RUN": str(failure_run),
        "HARNESS_STATS_PYTHON": sys.executable,
        "TMPDIR": str(snapshot_directory),
    }
    return repository, environment


def read_summary_rows(repository: Path) -> tuple[Path, list[dict[str, str]]]:
    """Return the only summary CSV generated by a fixture harness run."""
    summary_paths = list((repository / "harness_runs").glob("*/summary.csv"))
    assert len(summary_paths) == 1
    with summary_paths[0].open(encoding="utf-8", newline="") as summary_file:
        return summary_paths[0], list(csv.DictReader(summary_file))


def test_harness_continues_after_codex_failure_and_returns_nonzero(tmp_path: Path) -> None:
    repository, environment = create_harness_repository(tmp_path, failure_run=4)

    result = subprocess.run(
        ["scripts/run_harness.sh", "prompt.txt", "HEAD", "true", "5"],
        cwd=repository,
        env=environment,
        capture_output=True,
        encoding="utf-8",
    )

    _, rows = read_summary_rows(repository)
    assert result.returncode != 0
    assert [row["run"] for row in rows] == ["1", "2", "3", "4", "5"]
    assert rows[3]["run_status"] == "codex_failed"
    assert rows[3]["codex_exit_code"] == "7"
    assert rows[4]["run_status"] == "passed"
    assert list((repository / "harness_runs").glob("*/run_5.jsonl"))


def test_harness_preserves_post_check_stderr_in_check_log(tmp_path: Path) -> None:
    repository, environment = create_harness_repository(tmp_path, failure_run=99)

    result = subprocess.run(
        [
            "scripts/run_harness.sh",
            "prompt.txt",
            "HEAD",
            "sh -c 'echo post-check-detail >&2; exit 3'",
            "1",
        ],
        cwd=repository,
        env=environment,
        capture_output=True,
        encoding="utf-8",
    )

    summary_path, rows = read_summary_rows(repository)
    check_log = summary_path.parent / "run_1_check.log"
    assert result.returncode != 0
    assert rows[0]["run_status"] == "post_check_failed"
    assert rows[0]["post_check_exit_code"] == "3"
    assert check_log.read_text(encoding="utf-8") == "post-check-detail\n"


def test_harness_removes_ignored_python_caches_before_the_next_run(tmp_path: Path) -> None:
    repository, environment = create_harness_repository(tmp_path, failure_run=99)

    result = subprocess.run(
        ["scripts/run_harness.sh", "prompt.txt", "HEAD", "true", "2"],
        cwd=repository,
        env=environment,
        capture_output=True,
        encoding="utf-8",
    )

    _, rows = read_summary_rows(repository)
    assert result.returncode == 0
    assert [row["run_status"] for row in rows] == ["passed", "passed"]
    assert not (repository / "src" / "cache_only" / "__pycache__").exists()
    assert not (repository / "src" / "cache_only").exists()


def test_harness_uses_a_snapshot_when_codex_rewrites_the_live_script(tmp_path: Path) -> None:
    repository, environment = create_harness_repository(
        tmp_path, failure_run=99, mutate_harness_script=True
    )

    result = subprocess.run(
        ["scripts/run_harness.sh", "prompt.txt", "HEAD", "true", "1"],
        cwd=repository,
        env=environment,
        capture_output=True,
        encoding="utf-8",
    )

    summary_path, rows = read_summary_rows(repository)
    assert result.returncode == 0
    assert [row["run_status"] for row in rows] == ["passed"]
    assert "=== Done. Summary:" in result.stdout
    assert summary_path.exists()
    assert not list((tmp_path / "snapshots").glob("run_harness.*"))


def test_harness_ignores_an_inherited_snapshot_environment(tmp_path: Path) -> None:
    repository, environment = create_harness_repository(
        tmp_path, failure_run=99, mutate_harness_script=True
    )
    outer_snapshot = tmp_path / "snapshots" / "outer_snapshot"
    outer_snapshot.write_text("outer snapshot contents\n", encoding="utf-8")
    environment.update(
        {
            "HARNESS_SNAPSHOT_ACTIVE": "1",
            "HARNESS_SNAPSHOT_PATH": str(outer_snapshot),
            "HARNESS_SOURCE_SCRIPT": "/outside/repository/scripts/run_harness.sh",
        }
    )

    result = subprocess.run(
        ["scripts/run_harness.sh", "prompt.txt", "HEAD", "true", "1"],
        cwd=repository,
        env=environment,
        capture_output=True,
        encoding="utf-8",
    )

    _, rows = read_summary_rows(repository)
    assert result.returncode == 0
    assert [row["run_status"] for row in rows] == ["passed"]
    assert "=== Done. Summary:" in result.stdout
    assert outer_snapshot.read_text(encoding="utf-8") == "outer snapshot contents\n"
    assert not list((tmp_path / "snapshots").glob("run_harness.*"))
